import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/common/Sidebar";

const monseMontserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={monseMontserrat.className}>
        <div className="flex bg-[#FAFDFF] min-h-screen">
          <Sidebar />
          {children}
        </div>
      </body>
    </html>
  );
}
